using System.Collections.Generic;

namespace GwCopyPro.Services
{
    /// <summary>
    /// Central string table for English and German UI strings.
    /// Access localised strings with <c>L10n.T("key")</c>.
    /// Call <see cref="SetLanguage"/> once on startup or after a language change in Settings.
    /// </summary>
    public static class L10n
    {
        private static AppLanguage _lang = AppLanguage.English;

        /// <summary>Sets the active language for all subsequent calls to <see cref="T"/>.</summary>
        /// <param name="lang">The desired UI language.</param>
        public static void SetLanguage(AppLanguage lang) => _lang = lang;

        /// <summary>The currently active UI language.</summary>
        public static AppLanguage CurrentLanguage => _lang;

        /// <summary>
        /// Returns the localised string for <paramref name="key"/>.
        /// Falls back to <paramref name="key"/> itself when no entry is found.
        /// </summary>
        /// <param name="key">The string table key (e.g. <c>"app.title"</c>).</param>
        /// <returns>The localised string, or <paramref name="key"/> if not found.</returns>
        public static string T(string key) =>
            _lang == AppLanguage.German
                ? (_de.TryGetValue(key, out var de) ? de : key)
                : (_en.TryGetValue(key, out var en) ? en : key);

        private static readonly Dictionary<string, string> _en = new()
        {
            ["app.title"]              = "GW COPY PRO - by The8BitBox - Ilija Injac",
            ["app.devices"]            = "DEVICES",
            ["app.active_jobs"]        = "ACTIVE JOBS",
            ["app.ready"]              = "Ready",
            ["app.gw_path"]            = "gw.exe: {0}",

            ["btn.new_job"]            = "▶  New Job",
            ["btn.devices"]            = "⬡  Devices",
            ["btn.settings"]           = "⚙  Settings",
            ["btn.clear_done"]         = "✕  Clear Done",

            ["status.scanning"]        = "Scanning for GreaseWeazle devices…",
            ["status.no_devices"]      = "No GreaseWeazle devices found on startup.",
            ["status.querying_fw"]     = "Querying firmware on {0}…",
            ["status.detected"]        = "Auto-detected {0} GreaseWeazle device(s).",
            ["status.no_new"]          = "No new devices found.",
            ["status.detect_error"]    = "Auto-detect error: {0}",
            ["status.job_started"]     = "Job started: {0} – {1}",
            ["status.job_done"]        = "✓ Job completed: {0}",
            ["status.job_error"]       = "✗ Error: {0}",
            ["status.exception"]       = "Exception: {0}",
            ["status.jobs_count"]      = "{0} total, {1} running",

            ["nodev.label"]            = "No devices added. Click ⬡ Devices to add a GreaseWeazle.",

            ["job.cancel"]             = "✕  Cancel",
            ["job.view_log"]           = "📄  View Log",
            ["job.log_unavailable"]    = "Log not available yet. Job may not have started.",
            ["job.log_caption"]        = "Log",

            ["dev.connected"]          = "● Connected",
            ["dev.disconnected"]       = "● Disconnected",
            ["dev.remove"]             = "×",
            ["dev.new_job"]            = "▶ New Job",

            ["settings.title"]         = "Settings",
            ["settings.gw_exe"]        = "Path to gw.exe:",
            ["settings.browse"]        = "Browse…",
            ["settings.language"]      = "UI Language:",
            ["settings.lang_english"]  = "English",
            ["settings.lang_german"]   = "Deutsch",
            ["settings.restart_note"]  = "Language change takes effect after restarting the application.",
            ["settings.save"]          = "Save",
            ["settings.cancel"]        = "Cancel",
            ["settings.saved"]         = "Settings saved.",

            ["devmgr.title"]           = "Device Manager",
            ["devmgr.heading"]         = "Connected GreaseWeazle Devices",
            ["devmgr.auto_detect"]     = "⬡  Auto-Detect",
            ["devmgr.scanning"]        = "⬡  Scanning…",
            ["devmgr.col_name"]        = "Name",
            ["devmgr.col_port"]        = "Port",
            ["devmgr.col_fw"]          = "Firmware",
            ["devmgr.col_hwid"]        = "HW-ID",
            ["devmgr.col_status"]      = "Status",
            ["devmgr.port"]            = "Port:",
            ["devmgr.name"]            = "Name:",
            ["devmgr.add"]             = "+ Add",
            ["devmgr.remove"]          = "Remove Selected",
            ["devmgr.refresh"]         = "↻ Refresh Ports",
            ["devmgr.close"]           = "Close",
            ["devmgr.probe_hint"]      = "Select a COM port to probe firmware version.",
            ["devmgr.probing"]         = "Probing firmware on {0}…",
            ["devmgr.fw_result"]       = "{0} → Firmware: {1}",
            ["devmgr.none_found"]      = "No GreaseWeazle devices found. Check USB connection.",
            ["devmgr.detect_error"]    = "Detection error: {0}",
            ["devmgr.all_registered"]  = "All detected devices were already registered.",
            ["devmgr.added_n"]         = "Auto-detected {0} new device(s). Firmware queried.",
            ["devmgr.added_manual"]    = "Added {0} — Firmware: {1}",
            ["devmgr.missing_port"]    = "Select a COM port.",
            ["devmgr.status_ok"]       = "✓ Connected",
            ["devmgr.status_no"]       = "Disconnected",

            ["job_dlg.title"]          = "New GreaseWeazle Job",
            ["job_dlg.tab_main"]       = "Main Settings",
            ["job_dlg.tab_tracks"]     = "Track Selection",
            ["job_dlg.tab_advanced"]   = "Advanced",
            ["job_dlg.tab_postactions"]= "Post-Actions",
            ["job_dlg.device"]         = "Device:",
            ["job_dlg.job_type"]       = "Job Type:",
            ["job_dlg.read"]           = "Read (disk → image)",
            ["job_dlg.write"]          = "Write (image → disk)",
            ["job_dlg.image_file"]     = "Image File:",
            ["job_dlg.disk_format"]    = "Disk Format:",
            ["job_dlg.common_opts"]    = "─ Common Options ─",
            ["job_dlg.revs"]           = "Revolutions (--revs):",
            ["job_dlg.revs_hint"]      = "(flux revs per track, default 1)",
            ["job_dlg.densel"]         = "Density (--densel):",
            ["job_dlg.bitrate"]        = "  Bitrate (--bitrate):",
            ["job_dlg.bitrate_hint"]   = "(0=auto)",
            ["job_dlg.read_opts"]      = "─ Read Options ─",
            ["job_dlg.retries"]        = "--retries N:",
            ["job_dlg.no_clobber"]     = "--no-clobber",
            ["job_dlg.raw"]            = "--raw",
            ["job_dlg.reverse_read"]   = "--reverse (flippy side B)",
            ["job_dlg.hard_sectors"]   = "--hard-sectors",
            ["job_dlg.write_opts"]     = "─ Write Options ─",
            ["job_dlg.erase"]          = "--erase",
            ["job_dlg.verify"]         = "--verify",
            ["job_dlg.gen_tg43"]       = "--gen-tg43 (8\" drives)",
            ["job_dlg.precomp"]        = "--precomp:",
            ["job_dlg.reverse_write"]  = "--reverse",
            ["job_dlg.track_sel_head"] = "Track Selection  (builds --tracks=...)",
            ["job_dlg.track_info"]     = "gw.exe v0.24+ uses  --tracks=c=START-END:h=HEAD[:step=N][:hswap][:h0.off=N][:h1.off=N]\nThe old --scyl/--ecyl/--shead/--ehead flags are no longer valid.",
            ["job_dlg.cylinders"]      = "Cylinders (c=):",
            ["job_dlg.cyl_start"]      = "Start:",
            ["job_dlg.cyl_end"]        = "End:",
            ["job_dlg.cyl_hint"]       = "(0–79 = standard 80-track)",
            ["job_dlg.heads"]          = "Heads (h=):",
            ["job_dlg.heads_both"]     = "Both sides  (h=0-1)",
            ["job_dlg.heads_0"]        = "Head 0 only  (h=0)",
            ["job_dlg.heads_1"]        = "Head 1 only  (h=1)",
            ["job_dlg.step"]           = "Step (step=):",
            ["job_dlg.step_hint"]      = "(2 = read 40-track disk in 80-track drive)",
            ["job_dlg.hswap"]          = "hswap  (physical heads are swapped)",
            ["job_dlg.flippy_head"]    = "Flippy Drive Head Offsets",
            ["job_dlg.h0off"]          = "h0.off=",
            ["job_dlg.h0off_hint"]     = "(head 0 cylinder offset, for flippy-modded 5.25\" drives)",
            ["job_dlg.h1off"]          = "h1.off=",
            ["job_dlg.h1off_hint"]     = "(head 1 cylinder offset)",
            ["job_dlg.adv_head"]       = "Drive Selection & Extra Arguments",
            ["job_dlg.drive"]          = "--drive:",
            ["job_dlg.drive_hint"]     = "(drive letter or number on the GW bus)",
            ["job_dlg.extra_args"]     = "Extra Args:",
            ["job_dlg.token_note"]     = "Tokens available in Post-Action arguments:\r\n  {ImageFile}  — full path to the image file\r\n  {LogFolder}  — path to this job's log folder\r\n  {JobId}      — unique job ID string",
            ["job_dlg.pa_hint"]        = "Actions run sequentially after a successful job.  Tokens: {ImageFile}, {LogFolder}, {JobId}",
            ["job_dlg.pa_col_ord"]     = "#",
            ["job_dlg.pa_col_name"]    = "Name",
            ["job_dlg.pa_col_type"]    = "Type",
            ["job_dlg.pa_col_exe"]     = "Executable / Script",
            ["job_dlg.pa_col_args"]    = "Arguments",
            ["job_dlg.pa_col_en"]      = "En",
            ["job_dlg.pa_add"]         = "+ Add",
            ["job_dlg.pa_edit"]        = "Edit",
            ["job_dlg.pa_remove"]      = "Remove",
            ["job_dlg.start_job"]      = "▶  Start Job",
            ["job_dlg.cancel"]         = "Cancel",
            ["job_dlg.missing_image"]  = "Please specify an image file.",
            ["job_dlg.missing_image_cap"] = "Missing Image File",
            ["job_dlg.save_image"]     = "Save disk image as",
            ["job_dlg.open_image"]     = "Select disk image to write",
            ["job_dlg.auto_device"]    = "(Auto-select device)",

            ["pa_dlg.title"]           = "Post-Action",
            ["pa_dlg.name"]            = "Name:",
            ["pa_dlg.type"]            = "Type:",
            ["pa_dlg.type_exe"]        = "Executable",
            ["pa_dlg.type_bat"]        = "Batch Script",
            ["pa_dlg.type_ps1"]        = "PowerShell Script",
            ["pa_dlg.file"]            = "File:",
            ["pa_dlg.args"]            = "Arguments:",
            ["pa_dlg.enabled"]         = "Enabled",
            ["pa_dlg.ok"]              = "OK",
            ["pa_dlg.cancel"]          = "Cancel",

            ["job_dlg.tab_repeat"]         = "Repetitive",
            ["job_dlg.repeat_enabled"]     = "Repetitive mode (image sequence)",
            ["job_dlg.pattern_label"]      = "File Pattern:",
            ["job_dlg.pattern_hint"]       = "Tokens:  {n}  {n:D3}  {dt}   Example: Disk_{n:D3}_{dt}.scp",
            ["job_dlg.pattern_preview"]    = "Preview:",
            ["job_dlg.start_index"]        = "Start Index:",
            ["job_dlg.dt_format"]          = "DateTime format:",
            ["job_dlg.dt_format_hint"]     = "(C# DateTime format, e.g. yyyyMMdd_HHmmss)",
            ["job_dlg.repeat_note"]        = "The file pattern overrides the image file for each disk.\nAfter each disk a dialog will ask to insert the next one.",
            ["job_dlg.output_folder"]      = "Output Folder:",
            ["job_dlg.output_folder_hint"] = "(leave empty to use directory of Image File)",

            ["preset.save"]            = "💾  Save Preset",
            ["preset.load"]            = "📂  Load Preset",
            ["preset.save_title"]      = "Save Job Preset",
            ["preset.load_title"]      = "Load Job Preset",
            ["preset.filter"]          = "Job Preset (*.gwpreset)|*.gwpreset|All files (*.*)|*.*",
            ["preset.saved"]           = "Preset saved.",
            ["preset.loaded"]          = "Preset loaded.",
            ["preset.error_save"]      = "Could not save preset: {0}",
            ["preset.error_load"]      = "Could not load preset: {0}",

            ["nextdisk.title"]         = "Next Disk",
            ["nextdisk.done_disk"]     = "Disk #{0} completed successfully.",
            ["nextdisk.done_file"]     = "File: {0}",
            ["nextdisk.duration"]      = "Duration: {0:0.0} seconds",
            ["nextdisk.next_label"]    = "Next disk will be saved as:",
            ["nextdisk.dt_preview"]    = "Timestamp: {0}",
            ["nextdisk.waiting"]       = "Insert next disk and press ▶ Go",
            ["nextdisk.btn_go"]        = "▶  Go — next disk ready",
            ["nextdisk.btn_stop"]      = "✕  No more disks",

            ["job.restart"]            = "↺  Restart",
            ["job.disk_n"]             = "Disk #{0}",
        };

        private static readonly Dictionary<string, string> _de = new()
        {
            ["app.title"]              = "GW COPY PRO - By The8BitBox - Ilija Injac",
            ["app.devices"]            = "GERÄTE",
            ["app.active_jobs"]        = "AKTIVE AUFGABEN",
            ["app.ready"]              = "Bereit",
            ["app.gw_path"]            = "gw.exe: {0}",

            ["btn.new_job"]            = "▶  Neue Aufgabe",
            ["btn.devices"]            = "⬡  Geräte",
            ["btn.settings"]           = "⚙  Einstellungen",
            ["btn.clear_done"]         = "✕  Erledigte löschen",

            ["status.scanning"]        = "Suche nach GreaseWeazle-Geräten…",
            ["status.no_devices"]      = "Beim Start wurden keine GreaseWeazle-Geräte gefunden.",
            ["status.querying_fw"]     = "Firmware auf {0} wird abgefragt…",
            ["status.detected"]        = "{0} GreaseWeazle-Gerät(e) automatisch erkannt.",
            ["status.no_new"]          = "Keine neuen Geräte gefunden.",
            ["status.detect_error"]    = "Erkennungsfehler: {0}",
            ["status.job_started"]     = "Aufgabe gestartet: {0} – {1}",
            ["status.job_done"]        = "✓ Aufgabe abgeschlossen: {0}",
            ["status.job_error"]       = "✗ Fehler: {0}",
            ["status.exception"]       = "Ausnahme: {0}",
            ["status.jobs_count"]      = "{0} gesamt, {1} aktiv",

            ["nodev.label"]            = "Keine Geräte hinzugefügt. Klicken Sie auf ⬡ Geräte.",

            ["job.cancel"]             = "✕  Abbrechen",
            ["job.view_log"]           = "📄  Protokoll",
            ["job.log_unavailable"]    = "Protokoll noch nicht verfügbar. Die Aufgabe wurde möglicherweise noch nicht gestartet.",
            ["job.log_caption"]        = "Protokoll",

            ["dev.connected"]          = "● Verbunden",
            ["dev.disconnected"]       = "● Nicht verbunden",
            ["dev.remove"]             = "×",
            ["dev.new_job"]            = "▶ Neue Aufgabe",

            ["settings.title"]         = "Einstellungen",
            ["settings.gw_exe"]        = "Pfad zu gw.exe:",
            ["settings.browse"]        = "Durchsuchen…",
            ["settings.language"]      = "Sprache:",
            ["settings.lang_english"]  = "English",
            ["settings.lang_german"]   = "Deutsch",
            ["settings.restart_note"]  = "Die Sprachänderung wird nach einem Neustart der Anwendung wirksam.",
            ["settings.save"]          = "Speichern",
            ["settings.cancel"]        = "Abbrechen",
            ["settings.saved"]         = "Einstellungen gespeichert.",

            ["devmgr.title"]           = "Geräteverwaltung",
            ["devmgr.heading"]         = "Verbundene GreaseWeazle-Geräte",
            ["devmgr.auto_detect"]     = "⬡  Automatisch erkennen",
            ["devmgr.scanning"]        = "⬡  Suche läuft…",
            ["devmgr.col_name"]        = "Name",
            ["devmgr.col_port"]        = "Port",
            ["devmgr.col_fw"]          = "Firmware",
            ["devmgr.col_hwid"]        = "HW-ID",
            ["devmgr.col_status"]      = "Status",
            ["devmgr.port"]            = "Port:",
            ["devmgr.name"]            = "Name:",
            ["devmgr.add"]             = "+ Hinzufügen",
            ["devmgr.remove"]          = "Ausgewählte entfernen",
            ["devmgr.refresh"]         = "↻ Ports aktualisieren",
            ["devmgr.close"]           = "Schließen",
            ["devmgr.probe_hint"]      = "COM-Port auswählen, um Firmware abzufragen.",
            ["devmgr.probing"]         = "Firmware auf {0} wird abgefragt…",
            ["devmgr.fw_result"]       = "{0} → Firmware: {1}",
            ["devmgr.none_found"]      = "Keine GreaseWeazle-Geräte gefunden. USB-Verbindung prüfen.",
            ["devmgr.detect_error"]    = "Erkennungsfehler: {0}",
            ["devmgr.all_registered"]  = "Alle erkannten Geräte sind bereits registriert.",
            ["devmgr.added_n"]         = "{0} neues Gerät(e) erkannt. Firmware abgefragt.",
            ["devmgr.added_manual"]    = "{0} hinzugefügt — Firmware: {1}",
            ["devmgr.missing_port"]    = "Bitte COM-Port auswählen.",
            ["devmgr.status_ok"]       = "✓ Verbunden",
            ["devmgr.status_no"]       = "Nicht verbunden",

            ["job_dlg.title"]          = "Neue GreaseWeazle-Aufgabe",
            ["job_dlg.tab_main"]       = "Haupteinstellungen",
            ["job_dlg.tab_tracks"]     = "Spurauswahl",
            ["job_dlg.tab_advanced"]   = "Erweitert",
            ["job_dlg.tab_postactions"]= "Folgeaktionen",
            ["job_dlg.device"]         = "Gerät:",
            ["job_dlg.job_type"]       = "Aufgabentyp:",
            ["job_dlg.read"]           = "Lesen (Diskette → Abbild)",
            ["job_dlg.write"]          = "Schreiben (Abbild → Diskette)",
            ["job_dlg.image_file"]     = "Abbilddatei:",
            ["job_dlg.disk_format"]    = "Diskettenformat:",
            ["job_dlg.common_opts"]    = "─ Allgemeine Optionen ─",
            ["job_dlg.revs"]           = "Umdrehungen (--revs):",
            ["job_dlg.revs_hint"]      = "(Flux-Umdrehungen pro Spur, Standard 1)",
            ["job_dlg.densel"]         = "Dichte (--densel):",
            ["job_dlg.bitrate"]        = "  Bitrate (--bitrate):",
            ["job_dlg.bitrate_hint"]   = "(0=auto)",
            ["job_dlg.read_opts"]      = "─ Leseoptionen ─",
            ["job_dlg.retries"]        = "--retries N:",
            ["job_dlg.no_clobber"]     = "--no-clobber",
            ["job_dlg.raw"]            = "--raw",
            ["job_dlg.reverse_read"]   = "--reverse (Flippy Seite B)",
            ["job_dlg.hard_sectors"]   = "--hard-sectors",
            ["job_dlg.write_opts"]     = "─ Schreiboptionen ─",
            ["job_dlg.erase"]          = "--erase",
            ["job_dlg.verify"]         = "--verify",
            ["job_dlg.gen_tg43"]       = "--gen-tg43 (8\"-Laufwerke)",
            ["job_dlg.precomp"]        = "--precomp:",
            ["job_dlg.reverse_write"]  = "--reverse",
            ["job_dlg.track_sel_head"] = "Spurauswahl  (erstellt --tracks=...)",
            ["job_dlg.track_info"]     = "gw.exe v0.24+ verwendet  --tracks=c=START-END:h=HEAD[:step=N][:hswap][:h0.off=N][:h1.off=N]\nDie alten Flags --scyl/--ecyl/--shead/--ehead sind nicht mehr gültig.",
            ["job_dlg.cylinders"]      = "Zylinder (c=):",
            ["job_dlg.cyl_start"]      = "Start:",
            ["job_dlg.cyl_end"]        = "Ende:",
            ["job_dlg.cyl_hint"]       = "(0–79 = Standard 80-Spur)",
            ["job_dlg.heads"]          = "Köpfe (h=):",
            ["job_dlg.heads_both"]     = "Beide Seiten  (h=0-1)",
            ["job_dlg.heads_0"]        = "Nur Kopf 0  (h=0)",
            ["job_dlg.heads_1"]        = "Nur Kopf 1  (h=1)",
            ["job_dlg.step"]           = "Schritt (step=):",
            ["job_dlg.step_hint"]      = "(2 = 40-Spur-Disk in 80-Spur-Laufwerk)",
            ["job_dlg.hswap"]          = "hswap  (physische Köpfe vertauscht)",
            ["job_dlg.flippy_head"]    = "Flippy-Laufwerk Kopfversatz",
            ["job_dlg.h0off"]          = "h0.off=",
            ["job_dlg.h0off_hint"]     = "(Kopf-0-Zylinderversatz, für Flippy-modifizierte 5,25\"-Laufwerke)",
            ["job_dlg.h1off"]          = "h1.off=",
            ["job_dlg.h1off_hint"]     = "(Kopf-1-Zylinderversatz)",
            ["job_dlg.adv_head"]       = "Laufwerksauswahl & Zusatzargumente",
            ["job_dlg.drive"]          = "--drive:",
            ["job_dlg.drive_hint"]     = "(Laufwerksbuchstabe oder Nummer am GW-Bus)",
            ["job_dlg.extra_args"]     = "Zusätzliche Argumente:",
            ["job_dlg.token_note"]     = "Verfügbare Token in Folgeaktion-Argumenten:\r\n  {ImageFile}  — vollständiger Pfad zur Abbilddatei\r\n  {LogFolder}  — Pfad zum Protokollordner dieser Aufgabe\r\n  {JobId}      — eindeutige Aufgaben-ID",
            ["job_dlg.pa_hint"]        = "Aktionen laufen nach erfolgreicher Aufgabe sequenziell ab.  Token: {ImageFile}, {LogFolder}, {JobId}",
            ["job_dlg.pa_col_ord"]     = "#",
            ["job_dlg.pa_col_name"]    = "Name",
            ["job_dlg.pa_col_type"]    = "Typ",
            ["job_dlg.pa_col_exe"]     = "Programm / Skript",
            ["job_dlg.pa_col_args"]    = "Argumente",
            ["job_dlg.pa_col_en"]      = "Ak",
            ["job_dlg.pa_add"]         = "+ Hinzufügen",
            ["job_dlg.pa_edit"]        = "Bearbeiten",
            ["job_dlg.pa_remove"]      = "Entfernen",
            ["job_dlg.start_job"]      = "▶  Aufgabe starten",
            ["job_dlg.cancel"]         = "Abbrechen",
            ["job_dlg.missing_image"]  = "Bitte eine Abbilddatei angeben.",
            ["job_dlg.missing_image_cap"] = "Abbilddatei fehlt",
            ["job_dlg.save_image"]     = "Diskettenabbild speichern als",
            ["job_dlg.open_image"]     = "Diskettenabbild zum Schreiben auswählen",
            ["job_dlg.auto_device"]    = "(Gerät automatisch wählen)",

            ["pa_dlg.title"]           = "Folgeaktion",
            ["pa_dlg.name"]            = "Name:",
            ["pa_dlg.type"]            = "Typ:",
            ["pa_dlg.type_exe"]        = "Programm",
            ["pa_dlg.type_bat"]        = "Batch-Skript",
            ["pa_dlg.type_ps1"]        = "PowerShell-Skript",
            ["pa_dlg.file"]            = "Datei:",
            ["pa_dlg.args"]            = "Argumente:",
            ["pa_dlg.enabled"]         = "Aktiv",
            ["pa_dlg.ok"]              = "OK",
            ["pa_dlg.cancel"]          = "Abbrechen",

            ["job_dlg.tab_repeat"]         = "Wiederholen",
            ["job_dlg.repeat_enabled"]     = "Wiederholungsmodus (Bildfolge)",
            ["job_dlg.pattern_label"]      = "Dateimuster:",
            ["job_dlg.pattern_hint"]       = "Token:  {n}  {n:D3}  {dt}   Beispiel: Disk_{n:D3}_{dt}.scp",
            ["job_dlg.pattern_preview"]    = "Vorschau:",
            ["job_dlg.start_index"]        = "Startnummer:",
            ["job_dlg.dt_format"]          = "Datumsformat:",
            ["job_dlg.dt_format_hint"]     = "(C# DateTime-Format, z.B. yyyyMMdd_HHmmss)",
            ["job_dlg.repeat_note"]        = "Das Dateimuster ersetzt die Abbilddatei für jede Diskette.\nNach jeder Diskette erscheint ein Dialog für die nächste.",
            ["job_dlg.output_folder"]      = "Ausgabeordner:",
            ["job_dlg.output_folder_hint"] = "(leer lassen = Verzeichnis der Abbilddatei verwenden)",

            ["preset.save"]            = "💾  Preset speichern",
            ["preset.load"]            = "📂  Preset laden",
            ["preset.save_title"]      = "Aufgaben-Preset speichern",
            ["preset.load_title"]      = "Aufgaben-Preset laden",
            ["preset.filter"]          = "Aufgaben-Preset (*.gwpreset)|*.gwpreset|Alle Dateien (*.*)|*.*",
            ["preset.saved"]           = "Preset gespeichert.",
            ["preset.loaded"]          = "Preset geladen.",
            ["preset.error_save"]      = "Preset konnte nicht gespeichert werden: {0}",
            ["preset.error_load"]      = "Preset konnte nicht geladen werden: {0}",

            ["nextdisk.title"]         = "Nächste Diskette",
            ["nextdisk.done_disk"]     = "Diskette #{0} erfolgreich abgeschlossen.",
            ["nextdisk.done_file"]     = "Datei: {0}",
            ["nextdisk.duration"]      = "Dauer: {0:0.0} Sekunden",
            ["nextdisk.next_label"]    = "Nächste Diskette wird gespeichert als:",
            ["nextdisk.dt_preview"]    = "Zeitstempel: {0}",
            ["nextdisk.waiting"]       = "Nächste Diskette einlegen und ▶ Los drücken",
            ["nextdisk.btn_go"]        = "▶  Los — nächste Diskette bereit",
            ["nextdisk.btn_stop"]      = "✕  Keine weiteren Disketten",

            ["job.restart"]            = "↺  Neustart",
            ["job.disk_n"]             = "Disk #{0}",
        };
    }
}
